lib/gemcache/ruby/1.9.1/gems/railties-3.2.8/guides/code/getting_started/config/routes.rb
Blog::Application.routes.draw do
  resources :posts do
    resources :comments
  end

  get "home/index"

  root :to => "home#index"
  

end

lib/gemcache/ruby/1.9.1/gems/railties-3.2.8/guides/code/getting_started/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

lib/gemcache/ruby/1.9.1/gems/railties-3.2.8/guides/code/getting_started/app/models/post.rb
class Post < ActiveRecord::Base
  validates :name,  :presence => true
  validates :title, :presence => true,
                    :length => { :minimum => 5 }
 
  has_many :comments, :dependent => :destroy
  has_many :tags
 
  accepts_nested_attributes_for :tags, :allow_destroy => :true,
    :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }
end

lib/gemcache/ruby/1.9.1/gems/railties-3.2.8/guides/code/getting_started/app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :post
end

lib/gemcache/ruby/1.9.1/gems/railties-3.2.8/guides/code/getting_started/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

lib/gemcache/ruby/1.9.1/gems/railties-3.2.8/guides/code/getting_started/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	http_basic_authenticate_with :name => "dhh", :password => "secret", :only => :destroy
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment])
    redirect_to post_path(@post)
  end
 
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
 
end

lib/gemcache/ruby/1.9.1/gems/railties-3.2.8/guides/code/getting_started/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

lib/gemcache/ruby/1.9.1/gems/railties-3.2.8/guides/code/getting_started/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with :name => "dhh", :password => "secret", :except => :index
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

lib/gemcache/ruby/1.9.1/gems/railties-3.2.8/guides/code/getting_started/app/helpers/application_helper.rb
module ApplicationHelper
end

lib/gemcache/ruby/1.9.1/gems/railties-3.2.8/guides/code/getting_started/app/helpers/comments_helper.rb
module CommentsHelper
end

lib/gemcache/ruby/1.9.1/gems/railties-3.2.8/guides/code/getting_started/app/helpers/home_helper.rb
module HomeHelper
end

lib/gemcache/ruby/1.9.1/gems/railties-3.2.8/guides/code/getting_started/app/helpers/posts_helper.rb
module PostsHelper
  def join_tags(post)
    post.tags.map { |t| t.name }.join(", ")
  end
end

lib/gemcache/ruby/1.9.1/gems/railties-3.2.8/guides/code/getting_started/app/views/comments/_comment.html.erb
<p>
  <b>Commenter:</b>
  <%= comment.commenter %>
</p>
 
<p>
  <b>Comment:</b>
  <%= comment.body %>
</p>
 
<p>
  <%= link_to 'Destroy Comment', [comment.post, comment],
               :confirm => 'Are you sure?',
               :method => :delete %>
</p>

lib/gemcache/ruby/1.9.1/gems/railties-3.2.8/guides/code/getting_started/app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

lib/gemcache/ruby/1.9.1/gems/railties-3.2.8/guides/code/getting_started/app/views/home/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to "My Blog", posts_path %>

lib/gemcache/ruby/1.9.1/gems/railties-3.2.8/guides/code/getting_started/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

lib/gemcache/ruby/1.9.1/gems/railties-3.2.8/guides/code/getting_started/app/views/posts/_form.html.erb
<% @post.tags.build %>
<%= form_for(@post) do |post_form| %>
  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
  <div class="field">
    <%= post_form.label :name %><br />
    <%= post_form.text_field :name %>
  </div>
  <div class="field">
    <%= post_form.label :title %><br />
    <%= post_form.text_field :title %>
  </div>
  <div class="field">
    <%= post_form.label :content %><br />
    <%= post_form.text_area :content %>
  </div>
  <h2>Tags</h2>
  <%= render :partial => 'tags/form',
             :locals => {:form => post_form} %>
  <div class="actions">
    <%= post_form.submit %>
  </div>
<% end %>

lib/gemcache/ruby/1.9.1/gems/railties-3.2.8/guides/code/getting_started/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

lib/gemcache/ruby/1.9.1/gems/railties-3.2.8/guides/code/getting_started/app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.name %></td>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

lib/gemcache/ruby/1.9.1/gems/railties-3.2.8/guides/code/getting_started/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

lib/gemcache/ruby/1.9.1/gems/railties-3.2.8/guides/code/getting_started/app/views/posts/show.html.erb
<p class="notice"><%= notice %></p>
 
<p>
  <b>Name:</b>
  <%= @post.name %>
</p>
 
<p>
  <b>Title:</b>
  <%= @post.title %>
</p>
 
<p>
  <b>Content:</b>
  <%= @post.content %>
</p>
 
<p>
  <b>Tags:</b>
  <%= join_tags(@post) %>
</p>
 
<h2>Comments</h2>
<%= render @post.comments %>
 
<h2>Add a comment:</h2>
<%= render "comments/form" %>
 
 
<%= link_to 'Edit Post', edit_post_path(@post) %> |
<%= link_to 'Back to Posts', posts_path %> |